version: '3.7'
services:
  frontend:
    build:
      context: .
    expose:
      - "80"

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    expose:
      - "4100"
    volumes:
      - type: bind
        source: $HOME/myData
        target: /app/db
    depends_on:
      - backend
    environment:
      - SERVER_HOST=backend:4000
    restart: always

  backend:
    build:
      context: https://github.com/M1chlCZ/nsfw_sherlock.git#main
      dockerfile: Dockerfile
    expose:
      - "4000"
    restart: always

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - middleware
    restart: always