version: '3'
services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
  middleware:
    build:
      context: ./middleware
    ports:
      - "4100:4100"
  backend:
    build:
      context: https://github.com/M1chlCZ/nsfw_sherlock.git#main
      dockerfile: Dockerfile
    environment:
      - APP_ENV=grpc
    ports:
      - "4000:4000"