version: '3.7'
services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    volumes:
      - type: bind
        source: $HOME/myData
        target: /app/db
    depends_on:
      - backend
    environment:
      - SERVER_HOST=backend:4000
    restart: always
  backend:
    build:
      context: https://github.com/ProjectMerge/nsfw_sherlock.git#main
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
