// ignore_for_file: constant_identifier_names
bool isLoggedIn = false;
const String API_URL = 'http://localhost:4000';
const String AUTH_URL = 'http://localhost:4000';
const String EMAIL = "addr";
const String NAME = "username";
const String ID = "idUser";
const String ADR = "adr";
const String NICKNAME = "nickname";
const String LOCALE = "locale";
const String LEVEL = "level";
const String UDID = "udid";
const String TOKEN = "jwt";
const String TOKEN_DAO = "jwtDao";
const String TOKEN_REFRESH = "jwtRefresh";
const String PIN = "pin";
const String ADMINPRIV = "admin";
const String FIRETOKEN = "firetoken";
const String COUNTDOWN = "countdownTime";